### PR TITLE
Add screencasts #80

### PR DESCRIPTION
**Pull request by Vladimir-Tarasov**

### CODE REVIEW

**Comment by Vladimir-Tarasov** [comment]
@breslavsky check please

**Comment by breslavsky** [comment]
And you should add this videos to markdown please.

**Comment by Vladimir-Tarasov** [comment]
Video in **webm** format doesn't load. 

Screenshot 2023-03-15 at 11 25 49

**Comment by Vladimir-Tarasov** [comment]
@breslavsky check please

**Pull request merged**
